### ISSUE TITLE
Diffrent pin's with diffrent Command's 

### ISSUE THREAD

**Issue by salmanfarisvp** [ckuzma/nodemcu-as-arduino#3]
Can we control more pin's using alexa like the D1, i would like to use maximum gpio pin's on NodeMCU with different command's,

**Comment by ckuzma** [comment]
@salmanfarisvp It should be possible! It's something I'm looking into.

**Comment by salmanfarisvp** [comment]
@ckuzma ,in this code only two type input either 1 or 0, plz let me know if it's finished
